# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.knowledger:
  peer0.knowledger:
  peer1.knowledger:
  
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-knowledger
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.knowledger-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.knowledger-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/knowledger/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerKnowledger
    
  orderer.knowledger:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.knowledger
    container_name: orderer.knowledger
    
  peer0.knowledger:
    container_name: peer0.knowledger
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.knowledger
   
  peer1.knowledger:
    container_name: peer1.knowledger
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.knowledger