# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.knowledger:
    container_name: orderer.knowledger
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/knowledger/orderers/orderer.knowledger/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/knowledger/orderers/orderer.knowledger/tls/:/var/hyperledger/orderer/tls
    - orderer.knowledger:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.knowledger:
    container_name: peer0.knowledger
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.knowledger
      - CORE_PEER_ADDRESS=peer0.knowledger:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.knowledger:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.knowledger:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/knowledger/peers/peer0.knowledger/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/knowledger/peers/peer0.knowledger/tls:/etc/hyperledger/fabric/tls
        - peer0.knowledger:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.knowledger:
    container_name: peer1.knowledger
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.knowledger
      - CORE_PEER_ADDRESS=peer1.knowledger:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.knowledger:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.knowledger:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/knowledger/peers/peer1.knowledger/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/knowledger/peers/peer1.knowledger/tls:/etc/hyperledger/fabric/tls
        - peer1.knowledger:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  